//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int idAdministrator { get; set; }
        public string Communication { get; set; }
    
        public virtual People People { get; set; }
    }
}
