//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursovikTP : DbContext
    {
        public KursovikTP()
            : base("name=KursovikTP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrator> Administrator { get; set; }
        public DbSet<Applicant> Applicant { get; set; }
        public DbSet<Employer> Employer { get; set; }
        public DbSet<Jobs> Jobs { get; set; }
        public DbSet<People> People { get; set; }
        public DbSet<Resume> Resume { get; set; }
        public DbSet<Role> Role { get; set; }
    }
}
